name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  fmt:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: pypa/hatch@install
      - run: hatch check fmt
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: pypa/hatch@install
      - run: hatch check code
